language: ruby
before_script:
  - mysql -e 'create database cubecomp_test;'
script:
  - RAILS_ENV=test bundle exec rake db:setup db:migrate --trace
  - bundle exec rake db:test:prepare
  - bundle exec rake test
rvm:
  - 2.2.1
