language: ruby
before_script:
  - mkdir -p tmp/cubecomp/test/uploads/original
  - mysql -e 'create database cubecomp_test;'
  - mysql -e 'create database wca;'
script:
  - RAILS_ENV=test bundle exec rake db:setup db:migrate db:load_wca_schema --trace
  - bundle exec rake db:test:prepare
  - bundle exec rake test
rvm:
  - 2.2.1
notifications:
  email: false
