default: &default
  adapter: mysql2
  encoding: utf8
  host: 127.0.0.1
  password:
  pool: 5
  port: 3306
  username: root
  strict: true

development:
  <<: *default
  database: cubecomp_development
  # database: db/development.sqlite3

test:
  <<: *default
  database: cubecomp_test
  # database: db/test.sqlite3

wca:
  <<: *default
  database: wca
  # database: db/development.sqlite3
